### ISSUE TITLE
ライセンス明記

### ISSUE THREAD

**Issue by AknEp** [creasty-sandbox/form-php#1]
https://qiita.com/seihowlow24/items/debfd42a611c13664d57 こちらのQiitaの記事からやってきました。
数年メンテされていないようですが、品質的には今でも通用する内容のようで、こちらで実施している商用案件で利用させて頂きたいのですが、ライセンスの明記がなかったのでIssueで問合せ致しました。

Githubの機能で簡単に追加できるので、もし商用でも自由に使って構わないというお気持ちでしたら、MITやBSDの明記をして頂けると嬉しいです。

ライセンス明記方法については以下の記事が詳しいです。
https://qiita.com/shibukk/items/67ad0a5eda5a94e5c032

（※たまたまヒットしたのでQiitaの記事ばかりになりましたが、特にQiita信者とかではないです；）

**Comment by creasty** [comment]
ありがとうございます。かなり昔のやつなのでまだ使ってくれる人がいて驚きです。
内心、公開してるのが恥ずかしいのですが、、

一応、自分が作っている他の OSS 同様、MIT を明記するようにしました。
